#ifndef XTERM_PLUS_ANSI_PALETTE_H
#define XTERM_PLUS_ANSI_PALETTE_H

#define XTP_ANSI_PALETTE_SIZE 16U

#define XTP_ANSI_COLOR_0_DEFAULT "black"
#define XTP_ANSI_COLOR_1_DEFAULT "red3"
#define XTP_ANSI_COLOR_2_DEFAULT "green3"
#define XTP_ANSI_COLOR_3_DEFAULT "yellow3"
#define XTP_ANSI_COLOR_4_DEFAULT "blue2"
#define XTP_ANSI_COLOR_5_DEFAULT "magenta3"
#define XTP_ANSI_COLOR_6_DEFAULT "cyan3"
#define XTP_ANSI_COLOR_7_DEFAULT "gray90"
#define XTP_ANSI_COLOR_8_DEFAULT "gray50"
#define XTP_ANSI_COLOR_9_DEFAULT "red"
#define XTP_ANSI_COLOR_10_DEFAULT "green"
#define XTP_ANSI_COLOR_11_DEFAULT "yellow"
#define XTP_ANSI_COLOR_12_DEFAULT "rgb:5c/5c/ff"
#define XTP_ANSI_COLOR_13_DEFAULT "magenta"
#define XTP_ANSI_COLOR_14_DEFAULT "cyan"
#define XTP_ANSI_COLOR_15_DEFAULT "white"

#define XTP_ANSI_PALETTE_DEFAULT_LIST                                                              \
        XTP_ANSI_COLOR_0_DEFAULT, XTP_ANSI_COLOR_1_DEFAULT, XTP_ANSI_COLOR_2_DEFAULT,              \
            XTP_ANSI_COLOR_3_DEFAULT, XTP_ANSI_COLOR_4_DEFAULT, XTP_ANSI_COLOR_5_DEFAULT,          \
            XTP_ANSI_COLOR_6_DEFAULT, XTP_ANSI_COLOR_7_DEFAULT, XTP_ANSI_COLOR_8_DEFAULT,          \
            XTP_ANSI_COLOR_9_DEFAULT, XTP_ANSI_COLOR_10_DEFAULT, XTP_ANSI_COLOR_11_DEFAULT,        \
            XTP_ANSI_COLOR_12_DEFAULT, XTP_ANSI_COLOR_13_DEFAULT, XTP_ANSI_COLOR_14_DEFAULT,       \
            XTP_ANSI_COLOR_15_DEFAULT

#endif
