/* Generated by tools/generate-han-table; do not edit. */
/* clang-format off */
/* Unicode 17.0; Scripts.txt SHA-256 9f5e50d3abaee7d6ce09480f325c706f485ae3240912527e651954d2d6b035bf. */
#define XTP_HAN_UNICODE_VERSION "17.0"

static const XtpUnicodeRange xtp_han_ranges[] = {
    {0x002e80U, 0x002e99U},
    {0x002e9bU, 0x002ef3U},
    {0x002f00U, 0x002fd5U},
    {0x003005U, 0x003005U},
    {0x003007U, 0x003007U},
    {0x003021U, 0x003029U},
    {0x003038U, 0x00303aU},
    {0x00303bU, 0x00303bU},
    {0x003400U, 0x004dbfU},
    {0x004e00U, 0x009fffU},
    {0x00f900U, 0x00fa6dU},
    {0x00fa70U, 0x00fad9U},
    {0x016fe2U, 0x016fe2U},
    {0x016fe3U, 0x016fe3U},
    {0x016ff0U, 0x016ff1U},
    {0x016ff2U, 0x016ff3U},
    {0x016ff4U, 0x016ff6U},
    {0x020000U, 0x02a6dfU},
    {0x02a700U, 0x02b81dU},
    {0x02b820U, 0x02ceadU},
    {0x02ceb0U, 0x02ebe0U},
    {0x02ebf0U, 0x02ee5dU},
    {0x02f800U, 0x02fa1dU},
    {0x030000U, 0x03134aU},
    {0x031350U, 0x033479U},
};

/* clang-format on */
